#!/bin/bash

JAVA_OPTS="${JAVA_OPTS}"
JAVA_OPTS_LEGACY="${JAVA_OPTS_LEGACY}"

if [ -n "${JAVA_MEMORY_MAX}" ]; then
    JAVA_OPTS_LEGACY="${JAVA_OPTS_LEGACY} -Xmx${JAVA_MEMORY_MAX}"
fi
if [ -n "${JAVA_MEMORY_MIN}" ]; then
    JAVA_OPTS_LEGACY="${JAVA_OPTS_LEGACY} -Xms${JAVA_MEMORY_MIN}"
fi
if [ -n "${JAVA_XMX}" ]; then
    JAVA_OPTS_LEGACY="${JAVA_OPTS_LEGACY} -Xmx${JAVA_XMX}"
fi
if [ -n "${JAVA_XMS}" ]; then
    JAVA_OPTS_LEGACY="${JAVA_OPTS_LEGACY} -Xms${JAVA_XMS}"
fi


set -eu

set -- ${JAVA_OPTS} $@

for KEY in ${!JAVA_OPTS_@}; do
    set -- ${!KEY} $@
done

exec java "$@"
